### ISSUE TITLE
data.php restructure again soon

### ISSUE THREAD

**Issue by MichaelTunnell** [MichaelTunnell/las-picks#16]
I have realized that the weeks system is probably more effort than just typing the date in normally. In addition, if the date is typed in normally as I plan to then the year dataset is just redundant.

I've decided that I will now be removing the year element and converting the weeks element into a basic "date" format using yyyy-mm-dd as the syntax.

**Comment by testman42** [comment]
Good move.
And for reward, I give you this list of up-to-date Runs Linux picks.
https://docs.google.com/spreadsheets/d/1rrwqJPlOFZiDxxtQ7L3cb5rDYFdaOulJJ-oPryTXnY8/edit#gid=0

**Comment by MichaelTunnell** [comment]
Awesome, I started restructuring your spreadsheet last night to fit with the data of this project and then I come back to see that you have populated the content for the structure...SO COOL!

Thank you for helping with this effort.

I found a few issues with your spreadsheet though. S11E05 and S11E06 both had Runs Linux picks but you missed them because back then the shownotes were completely awful. In one of the episodes they didnt even mention that is what they were talking about so it required me to rewatch the episode to see if there was an app pick.

The above issue was not your fault obviously, the shownotes were just terrible then. If there is any empty slot for episode please watch the episode a bit to find if it does have one or not.

------

Oh cool you added 1-40. There is an ods with content for that...did you use that for populating the gdoc spreadsheet?

**Comment by testman42** [comment]
Yes, I used your ods file, and I also cited it in first line as source. (Actually whole your ods file is in gdoc spreadsheet, but lines without Linux picks are hidden)

And yes, it took me quite some time to make all the copypasta, I really did not have time to watch episodes. Will probably do that soon. And I am grateful for effort on your part.

**Comment by MichaelTunnell** [comment]
Yea you have no idea how much of a help this is to the site. This consolidation of data is a huge improvement to the effort to add picks.

In fact the structure will allow the other picks to be even faster as the episode data will already be available thanks to this combination of effort.

Thank you very much for participating . . . the watching thing is not necessary I was just explaining how I found those two picks and that there might be more. If you don't have time to watch them then that is just fine, you have already saved me a lot of time and effort in data collection so I'm sure I can deal with watching a few episodes to see if there are picks or not. :)

**Comment by allanjude** [comment]
The data.php format is hard to work with.

At a minimum, it would seem to make sense to have:

// Episode 345
$data[345]['title'] = "2015 Linux Predictions | LAS 345";
$data[345]['url'] = "http://www.jupiterbroadcasting.com/74497/2015-linux-predictions-linux-action-show-345/";
$data[345]['year'] = "2014";
$data[345]['week'] = "+51 weeks";

replaced with:


// Episode 345
$data[] = array(
  'title' => "2015 Linux Predictions | LAS 345",
  'url' => "http://www.jupiterbroadcasting.com/74497/2015-linux-predictions-linux-action-show-345/",
  'year' => "2014",
  'week' => "+51 weeks",
);

Just to avoid repeating yourself so many times, or having to manually track the index.

**Comment by thorhop** [comment]
Søndag 4. januar 2015 17.35.29 skrev Allan Jude:

I second this - while wearing a red veluer robe, a fez and smoking a soap-
bubble pipe... yes. Clean code is easily read code. Easily read code is less 
proned to cause cock-ups. And we're not at home for Mr Cockup.

**Comment by MichaelTunnell** [comment]
Allan's suggestion is not simpler to read. If a person has never seen a data structure before neither will be easy and they will need to learn the syntax. Either way it doesn't matter in that case.

The current structure is designed to compensate for mistakes. If someone adds an item to the data set and they screw up on anything it breaks nothing but that single item.

If someone screws up on a JSON structure they break the entire thing. If someone screws up on Allan's suggestion then they only break the individual array the messed up on but I dont see how that is a benefit at all.

Which one is easier to read just boils down to the individual and opinion. I think the php structure is easier and others think the JSON style or faux-JSON in PHP is easier. I politely disagree and if a case can't be made to change my mind I suppose that solves that.

I have restructured the data slightly to remove useless elements but it is still in the same syntax for those interested.

**Comment by TimoDJatomika** [comment]
off-topic: but have you consider using a database instead of this file?

**Comment by MichaelTunnell** [comment]
In my opinion, a database would be massive overkill with no real benefit.
The current structure is not hard to use, I just haven't had a lot of time
to do it.
