### ISSUE TITLE
push latest data from server to GitHub

### ISSUE THREAD

**Issue by MichaelTunnell** [MichaelTunnell/las-picks#26]
The data file on the server is out of date to the GitHub repo so I need to push the latest content to the GitHub repo to keep it in sync.

**Comment by toXel** [comment]
+1!

**Comment by Gyges88** [comment]
Considering bringing Laspicks up to date, I just realized the latest data is still missing.

**Comment by MichaelTunnell** [comment]
I know. I am just swamped for time and have been for the past couple of months. I'll get to it this weekend hopefully.

**Comment by Gyges88** [comment]
I know ;-)
Don't consider yourself rushed, I just commented as a reminder, because 
the bigger the gap gets, the more painful it gets to bring it up to date.
By the way, that's a very nice layout you've composed for full-video 
LAS. I like!


Am 21.01.2016 um 23:06 schrieb Michael Tunnell:

**Comment by hubertbanas** [comment]
@MichaelTunnell any updates on this? I was going to help keep it up-to-data.

**Comment by MichaelTunnell** [comment]
thanks to @htesligte for helping update the data array, this issue is now solved.
