### ISSUE TITLE
Distros Page Doesn't Display Correctly

### ISSUE THREAD

**Issue by computerfr33k** [MichaelTunnell/las-picks#31]
There is an issue when displaying the distros page, probably missing stuff in the array for episodes.
![screenshot from 2016-02-15 00-27-36](https://cloud.githubusercontent.com/assets/2096910/13041225/e41e0e0a-d37a-11e5-92b9-4135c0324433.png)

**Comment by MichaelTunnell** [comment]
The Distros page works just fine, I have no idea what las-picks.app is because that is not the location of the website.

http://jupiterbroadcasting.com/laspicks/distros.php

**Comment by computerfr33k** [comment]
its just a local domain name in my /etc/hosts file.

Not sure how the latest master works for you, if you could explain to me 
what I am doing wrong so I can get it to work. But it looks like its 
erroring on missing array indexes.

Also, that VM is using php 7, but I find it hard to believe that PHP 7 
would be the cause of the issue.

**Comment by MichaelTunnell** [comment]
There is no reason as to why that wont work because it looks like it is breaking for an index on the data array but the array is fine and so there isn't a reason why it would break. I do have plans for restructuring the data array so that might fix it.

**Comment by computerfr33k** [comment]
One thing I think that might help with the data storage would be to store it in json format which would be easy to parse and loop through. Not sure if that's one thing you were thinking of storing the data in so you wouldn't have to manually type out and assign elements into a large php array.

**Comment by MichaelTunnell** [comment]
> One thing I think that might help with the data storage would be to store it in json format which would be easy to parse and loop through.

JSON has already been suggested and I have already explained why that is not a good option, essentially boiling down to complete breakage by possible contributors. https://github.com/MichaelTunnell/las-picks/issues/16#issuecomment-69358945

> wouldn't have to manually type out and assign elements into a large php array.

Yea you would only have to manually type out and assign elements in a large JSON format. It doesn't really improve much at all, all it does it change how the data is laid out.

I have considered converting it into a JSON style PHP array so it's still PHP but flows more like JSON, but of course still wouldn't be JSON.

**Comment by computerfr33k** [comment]
So after trying it on my production environment running CentOS & PHP 5.6 it worked, but when running in my dev environment with PHP 7 it doesn't work. So for some reason there is an issue when running on PHP 7, at least for me.

**Comment by MichaelTunnell** [comment]
That's interesting. I will not have time to check that out for a while but I would be upgrading to PHP6 instead of 7 anyway so it will be a very long time before that will be an issue for the main site.

**Comment by computerfr33k** [comment]
I don't think there even is an official release anymore for PHP 6 because some of the history during its development. And there is no PHP 6 listen on the website. And so the next version is PHP 7. Just thought I'd let you know. But I also wouldn't upgrade my production sites to PHP 7 for a few more years now.
