### ISSUE TITLE
Workflow explained - from accepting PR to website going live

### ISSUE THREAD

**Issue by hubertbanas** [MichaelTunnell/las-picks#39]
I see the master is up-to-date but the website is still lacking the last episode. 

@MichaelTunnell would you mind explaining the workflow starting from accepted PR to the website going live?

In other words is there a git hook from this repo or is it manual push to the web server?

**Comment by MichaelTunnell** [comment]
1. The workflow is essentially GitHub gets updated.
2. I push current code to development server to test for issues.
3. If no issues, I push to the live server.

It's not updated on the website because I have not push it to the live server yet. That's my fault but lots to do lately. :)

I'll get it added tomorrow or Thursday at the latest.

**Comment by hubertbanas** [comment]
Thanks for this detailed explanation. Let me know if you need any help with any of the highlighted steps.

Have you considered automating any of it? Maybe starting with 1 and 2 for now?

**Comment by MichaelTunnell** [comment]
everything has been pushed live now. :) I know that took way too long.

**Comment by hubertbanas** [comment]
Good to hear it. Have you considered improving the process of the production web going live? I'm here to help and open for discussion.

**Comment by MichaelTunnell** [comment]
There really isnt much that can be done. Unless I automate the process from when something is added to git it gets added to the site but I typically have to manually test first. It's cool that you set a test version but you are the only one who has done that. :)

We can test my current setup after this next episode tomorrow and see how fast the turnaround time can be with my current changes.
