### ISSUE TITLE
What if? (Rewrite that bash script in python to push to API?)

### ISSUE THREAD

**Issue by AffableZonkey** [MichaelTunnell/las-picks#45]
Michael - what if I rewrote that crappy bash script in python to update to the json API? I could just add a blank entry for the Android pick, that way someone could just pop it in with a pull request or something?

**Comment by MichaelTunnell** [comment]
I suppose if you'd like to do that I could add it to the repo as a tool to use but it would require users to still manually pull the info locally. I'm thinking of making a PHP file that does it on the site and outputs the code on the server.

**Comment by gr3yman** [comment]
Sorry - just got around to checking on this..were you planning on starting to work on this soon?

**Comment by MichaelTunnell** [comment]
I don't know about how soon I would start.

**Comment by MichaelTunnell** [comment]
Closing this because the Linux Action Show is cancelled.
