### ISSUE TITLE
Possible Array Restructuring, Thoughts?

### ISSUE THREAD

**Issue by MichaelTunnell** [MichaelTunnell/las-picks#62]
I am considering doing a restructuring of the $data array in order to eliminate some of the manual input such as manually tracking indexes. I've created two different gists one containing 424 data with the current structure and the other containing 424 with the restructuring.

Which structure do you prefer?
Which structure looks the easiest to use?
Which structure do you think has the lowest learning curve?

Current: https://gist.github.com/MichaelTunnell/6961b69503b95338c91d723f3d69dda5

Restructured: https://gist.github.com/MichaelTunnell/6fb1497b797933049c5a76bc86d79e5b

@hubertbanas @thefenriswolf @htesligte

**Comment by htesligte** [comment]
Well, if you want to keep it in plain PHP, you could also use [] for array's, that might make it look a bit cleaner. I would be more in favour of structuring the data in a format like json, xml or something like that. But I believe you like to keep it in PHP.
So maybe a compromise might be writing the data in e.g. json and then generating PHP code with var_export?

To answer your questions directly: 
Which structure do you prefer?
I am a fulltime PHP developer and never specify array keys when I use numeric array's, so the second one :)

Which structure looks the easiest to use?
I think for someone just starting out it is a bit easier to see the numeric keys, but anyone who has played with PHP for a couple of hours shoud be comfortable with the second way.

Which structure do you think has the lowest learning curve?
I'm not sure.. I wouldn't learn a programming language by trying to understand this. So I guess I don't really have an answer there.

**Comment by MichaelTunnell** [comment]
> Well, if you want to keep it in plain PHP, you could also use [] for array's, that might make it look a bit cleaner.

I'm suggesting doing that, any suggestions to improve the restructured autoindex version?

> I would be more in favour of structuring the data in a format like json, xml or something like that. But I believe you like to keep it in PHP.

The reason for the PHP instead of JSON is because if anything breaks in JSON then **everything** breaks. Using PHP instead allows for only one episode to break instead of everything. That's pretty much the only reason . . . well and no need to convert the data to PHP when using it.

----

Thank you for the feedback and answering my questions.

**Comment by htesligte** [comment]
> I'm suggesting doing that, any suggestions to improve the restructured autoindex version?
I'm sorry, [this](https://gist.github.com/htesligte/9ea202db410b32103f9ec8fa7a6ea64f) is what I meant by []'s :)

> The reason for the PHP instead of JSON is because if anything breaks in JSON then everything breaks. 
I see. JSON is pretty strict indeed.. And I guess you would find writing a whole new solution with an interface to force correct user input a bit too overboard ;) 
How about keeping separate files for each episode? 

My (humble ;)) opinion:
To be honest, I don't really like the way the episode file is growing over time, and so I would look at creating a simple interface that allows users to submit the data and then store it somehow. I guess my alternative way would be to create a simple OOP structure that forces correct user input. But maybe someone else has some great ideas?

**Comment by MichaelTunnell** [comment]
@thefenriswolf @hubertbanas please review this discussion. I'm curious to get your thoughts.

**Comment by thefenriswolf** [comment]
Well, I'm not a developer so as far as technology goes I simply can not tell which structure is better.

As far as I can tell with the restructured version i has become obsolete to insert the Episode  Number like 10 times.

Furthermore, you've added the android pick again for some reason?

As far as the "learning curve" and "ease of use" goes, I think new contributors can adapt to the array-based structure so thats not really an issue.

I also think @htesligte is right, the data.php file is growing fast and will soon be a pain in the b***!

**Comment by hubertbanas** [comment]
Both formats can be easy or difficult ... depends how you look at it. I agree that we should split each episode into its own data file ex:
Episode 2 data file: _1.php_
Episode 2 data file: _2.php_
etc

These files should be located in their own directory so they don't pollute main directory

**Comment by MichaelTunnell** [comment]
@thefenriswolf 
> Well, I'm not a developer so as far as technology goes I simply can not tell which structure is better.

I know, that's actually why I want your opinion. What I see as easy would be different from what you might see as not being a developer. :)

> As far as I can tell with the restructured version i has become obsolete to insert the Episode Number like 10 times.

yes, it simplifies the structure so there will no longer be any need to keep track of the episode number manually.

> Furthermore, you've added the android pick again for some reason?

Nope, I posted this discussion in July. We decided to remove Android picks after I made this discussion.

> I also think @htesligte is right, the data.php file is growing fast and will soon be a pain in the b***!

I agree, it will eventually get messy. Especially without tracking the episode numbers.

@hubertbanas 
>I agree that we should split each episode into its own data file ex:
>These files should be located in their own directory so they don't pollute main directory

I agree that it probably needs to be split up but I don't want to split them into each episode as that would be just as daunting eventually.

How about each year is split into a different episode so each data file has 52 episodes in it?

**Comment by hubertbanas** [comment]
> How about each year is split into a different episode so each data file has 52 episodes in it?

That will work too.

**Comment by MichaelTunnell** [comment]
Closing this because the Linux Action Show is canceled.
