### ISSUE TITLE
LAS Cancelling

### ISSUE THREAD

**Issue by MichaelTunnell** [MichaelTunnell/las-picks#90]
As I am sure you are all aware by now, Linux Action Show is being canceled and with it we can only assume the Picks segment is gone as well.

Thank you all so much for helping with this project and keeping it up to date! I couldn't have done without all the contributions from everyone!

I plan to continue updating the page until the show is canceled so until then the project won't be closed but I expect that there will be no need for the project to continue after the last episode of LAS.

It might be possible that the picks are moved to a different show but as of yet it has not be stated whether or not that will happen. I suspect it won't though.

Anyway, thanks again with helping with this project. I very much appreciate everyone contributing!

**Comment by htesligte** [comment]
Lol, I missed the last couple of shows and now they are being canceled :-1: Well, we'll see what happens, if you like my input for a different project feel free to ping me :)

**Comment by cinnamoner** [comment]
@MichaelTunnell Is LAS cancelled for good? I've been following the Picks for a long time. It's been a great job. 👍

**Comment by MichaelTunnell** [comment]
@htesligte 
> Lol, I missed the last couple of shows and now the show is being canceled

It was incredibly abrupt announcement for sure.

>  if you like my input for a different project feel free to ping me

That would be fantastic. I very much appreciate your offer.

I do have something that I am working on that might be beneficial to have help with data management when it gets to launch stage.

---------------

@cinnamoner 
> Is LAS cancelled for good? I've been following the Picks for a long time. It's been a great job.

I don't know for sure but based on the way Chris announced it . . . probably.

Thanks for the kind words and I couldn't have done it all alone. :) I did make the picks site and stuff on my own but the data management was a huge task and so many people stepped up to help and I am super grateful to them all.

**Comment by MichaelTunnell** [comment]
The show is now over so there is no need for this project to continue. I am closing this issue now. Episode 468 still needs to be added but the episode hasn't been published yet.
